{% set name = "apache-airflow-providers-slack" %}
{% set version = "8.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_slack-{{ version }}.tar.gz
  sha256: 197c191be9f40885c85e124dec68d0121784d82d0cd06f5665b37087008cb77f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.1
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow-providers-common-sql >=1.20.0
    - apache-airflow >=2.8.0
    - slack_sdk >=3.19.0

test:
  imports:
    - airflow.providers.slack
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-slack for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/slack/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-slack/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
