{% set name = "apache-airflow-providers-slack" %}
{% set version = "8.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_slack-{{ version }}.tar.gz
  sha256: d61fa258a85d4d5a33e5e9208b73635c675cb23e1983dbb075367ed3a46f0b41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.8.0
    - slack_sdk >=3.19.0

test:
  imports:
    - airflow.providers.slack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-slack for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/slack/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-slack/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
